language: node_js
node_js:
  - 0.11
  - 6
  - 8
  - 10
before_install:
  - npm install -g npm@2.15.0
after_success:
  - npm install -g nyc@8.4.0
  - npm install -g codecov
  - nyc --reporter lcov npm test && codecov
